"""schema inicial

Revision ID: df3a921b07c8
Revises: 
Create Date: 2026-07-08 21:51:57.252949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3a921b07c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativas_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_tentado', sa.String(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('ip_origem', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bastao_atual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('desde', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_bastao_atual_singleton'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bastao_transferencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('para_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['de_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['para_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contadores_bastao',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rodadas', sa.Integer(), nullable=False),
    sa.Column('tempo_total_segundos', sa.BigInteger(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('demandas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=False),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('criado_por', sa.Uuid(), nullable=True),
    sa.Column('direcionada_para', sa.Uuid(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['direcionada_para'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fila_posicoes',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('posicao', name='uq_fila_posicao')
    )
    op.create_table('jogo_simon_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_origem', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('status_colaborador',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('status_tipo', sa.Enum('na_fila', 'almoco', 'saida_rapida', 'ausente', 'em_demanda', 'indisponivel', name='status_tipo'), nullable=False),
    sa.Column('status_detalhe', sa.Text(), nullable=True),
    sa.Column('status_desde', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('atividades_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=True),
    sa.Column('atividade_texto', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duracao_minutos', sa.Float(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demanda_id'], ['demandas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividades_log')
    op.drop_table('status_colaborador')
    op.drop_table('sessoes')
    op.drop_table('jogo_simon_scores')
    op.drop_table('fila_posicoes')
    op.drop_table('eventos_log')
    op.drop_table('demandas')
    op.drop_table('contadores_bastao')
    op.drop_table('bastao_transferencias')
    op.drop_table('bastao_atual')
    op.drop_table('usuarios')
    op.drop_table('tentativas_login')
    # ### end Alembic commands ###
